name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment for JavaScript/React
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 

    - name: Install Node.js dependencies
      run: npm install

    # Set up Python environment for backend
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: npm test && pytest 

    # Build and push Docker image (if using Docker)
    - name: Login to Heroku Container Registry
      uses: heroku/heroku-container-registry@v1 # Corrected version here
      with:
        email: ${{ secrets.HEROKU_EMAIL }} 
        password: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
