name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment for JavaScript/React
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node.js dependencies
      run: npm install

    # Set up Python environment for backend
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: npm test && pytest

    # Build and push Docker image
    - name: Login to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build and push Docker image to Heroku
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
